### ISSUE TITLE
And "BRAVE NEW WORLD" text contain

### ISSUE THREAD

**Issue by childx** [AlberTajuelo/bitcoin-0.2-image-puzzle#4]
B
We define an electronic coin as a chain of digital signatures. Each owner transfers the coin to the next by digitally signing

R
a hash of the previous transaction and the public key of the next owner and adding these to the end of the coin.

A
A payee can verify the signatures to verify the chain of ownership.

V
The problem of course is the payee can't verify that one of the owners did not double-spend
the coin.

E
A common solution is to introduce a trusted central authority, or mint, that checks every transaction for double spending

N
After each transaction, the coin must be returned to the mint to

E
issue a new coin, and only coins issued directly from the mint are trusted not to be double-spent.

W
The problem with this solution is that the fate of the entire money system depends on thecompany running the mint,

W
with every transaction having to go through them, just like a bank

O
We need a way for the payee to know that the previous owners did not sign any earlier transactions.

R
For our purposes, the earliest transaction is the one that counts

L
so we don't care about later attempts to double-spend

D
The only way to confirm the absence of a transaction is to
be aware of all transactions.

**Comment by AlberTajuelo** [comment]
This has already added to the repository. I'm closing this issue.

https://github.com/AlberTajuelo/bitcoin-0.2-image-puzzle?tab=readme-ov-file#14-welcome-to-the-brave-new-world
